/** RocketChat DDP Request type */
export interface IServerRequest {
  _id: string // generated by Random.id()
  u: {
    _id: string
    username: string
  }
  key: string
  ts: Date
  data?: object
}

/** Structure of the object to reply to a DDP Request */
export interface IServerRequestResponse {
  success: boolean
  error?: Error
  data?: object
}

/** Prototype of a function that handles a DDP Request */
export interface IServerRequestHandler {
  (command: IServerRequest): Promise<IServerRequestResponse>
}

/** Structure of a map of handlers, - add types to avoid TSLint errors */
export interface IServerRequestHandlerMap {
  [key: string]: IServerRequestHandler
}

/** Structure of the object of client data */
export interface ICustomClientData {
  stack: Array<IClientDetails>
  [key: string]: any
}

export interface IClientDetails {
  name: string
  version: string
}
